---
- name: configure local facts, install pexpect and epel-release
  include: pre.yml

- name: install and configure firewalls
  environment:
    PATH: /usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/bin
  include: firewall.yml
  when: include_firewall is true

- name: configure sysctl
  include: sysctl.yml
  when: include_sysctl is true

- name: disable kernel network modules
  include: disablenet.yml
  when: include_disablenet is true

- name: disable file system kernel modules
  include: disablefs.yml
  when: include_disablefs is true

- name: configure systemd system and users
  include: systemdconf.yml
  when: include_systemdconf is true

- name: configure systemd journald and logrotate
  include: journalconf.yml
  when: include_journalconf is true

- name: configure systemd timesyncd
  include: timesyncd.yml
  when: include_timesyncd is true

- name: clean fstab
  include: fstab.yml
  when: include_fstab is true

- name: configure shm and tmp mounts
  include: mount.yml
  when: include_mount is true

- name: disable prelink
  include: prelink.yml
  when: include_prelink is true

- name: configure package managers, update caches and install updates
  include: packagemgmt.yml
  when: include_packagemgmt is true

- name: configure hosts.allow and hosts.deny
  include: hosts.yml
  when: include_hosts is true

- name: configure login.defs
  include: logindefs.yml
  when: include_logindefs is true

- name: set limits
  include: limits.yml
  when: include_limits is true

- name: configure adduser and useradd
  include: adduser.yml
  when: include_adduser is true

- name: restrict root access
  include: rootaccess.yml
  when: include_rootaccess is true

- name: configure needrestart, install and remove various packages
  environment:
    PATH: /usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/bin
  include: packages.yml
  when: include_packages is true

- name: configure ssh server and client
  include: sshconfig.yml
  when: include_sshconfig is true

- name: configure pam
  include: password.yml
  when: include_password is true

- name: configure and clean at and cron
  include: cron.yml
  when: include_cron is true

- name: disable ctrl-alt-del.target
  include: ctrlaltdel.yml
  when: include_ctrlaltdel is true

- name: configure auditd
  include: auditd.yml
  when: include_auditd is true

- name: configure apparmor
  environment:
    PATH: /usr/sbin:/sbin:/usr/local/sbin:/usr/local/bin:/bin
  include: apparmor.yml
  when: include_apparmor is true

- name: disable misc kernel modules
  include: disablemod.yml
  when: include_disablemod is true

#   https://bugs.launchpad.net/ubuntu/+source/aide/+bug/1903298
- name: configure aide
  include: aide.yml
  when:
    - install_aide|bool and (not (ansible_distribution == "Ubuntu" and (ansible_lsb.codename == "groovy" or ansible_lsb.codename == "hirsute")))
    - include_aide is true

- name: remove users
  include: users.yml
  when: include_users is true

- name: remove suid/sgid
  include: suid.yml
  when:
    - suid_sgid_permissions|bool
    - include_suid is true

- name: configure compiler permissions
  include: compilers.yml
  when: include_compilers is true

- name: set umask
  include: umask.yml
  when: include_umask is true

- name: configure paths
  include: path.yml
  when: include_path is true

- name: configure systemd logindconf
  include: logindconf.yml
  when: include_logindconf is true

- name: configure systemd resolvedconf
  include: resolvedconf.yml
  when: include_resolvedconf is true

- name: configure rkhunter
  include: rkhunter.yml
  when: include_rkhunter is true

- name: add issue message
  include: issue.yml
  when: include_issue is true

- name: disable apport
  include: apport.yml
  when: include_apport is true

- name: lock root account
  include: lockroot.yml
  when: include_lockroot is true

- name: configure postfix
  include: postfix.yml
  when: include_postfix is true

- name: configure motdnews
  include: motdnews.yml
  when: include_motdnews is true

- name: configure sudo
  include: sudo.yml
  when: include_sudo is true

- name: misc extra tasks
  include: extras.yml
  when: include_extras is true

- name: misc tasks after all handlers
  include: post.yml
  when: include_post is true
...
